apiVersion: apps/v1
kind: Deployment
metadata:
  name: tour-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tour-project
  template:
    metadata:
      labels:
        app: tour-project
    spec:
      containers:
      - name: tour-project
        image: sidhopant/tour-project:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tour-project-service
spec:
  type: NodePort
  selector:
    app: tour-project
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
